// Package materialize writes the generated parts of a workspace: .ipalpha/bin/ipalpha (a copy of
// this binary), the ./run ./pull ./publish ./feature ./set-keys wrappers for every shell, embedded
// helper files, and the agent instruction pointers. It also removes what the bash tooling left.
package materialize

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ipalpha-dev/tooling/internal/assets"
	"github.com/ipalpha-dev/tooling/internal/envfile"
	"github.com/ipalpha-dev/tooling/internal/infra"
	"github.com/ipalpha-dev/tooling/internal/sys"
	"github.com/ipalpha-dev/tooling/internal/workspace"
)

// Commands get a wrapper at the workspace root.
var Commands = []string{"run", "stop", "status", "logs", "pull", "publish", "feature", "set-keys", "doctor", "ipalpha"}

// BinPath is the workspace copy of the binary.
func BinPath(w *workspace.Workspace) string {
	return filepath.Join(w.Dir(), "bin", "ipalpha"+sys.ExeSuffix())
}

// Write materializes everything. self is the running binary (copied unless it already is the copy).
func Write(w *workspace.Workspace, self string) error {
	for _, d := range []string{w.Dir(), filepath.Join(w.Dir(), "bin"), w.StateDir(), w.LogsDir()} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	cleanLegacy(w)
	if err := InstallBinary(self, BinPath(w)); err != nil {
		return fmt.Errorf("copy the ipalpha binary into .ipalpha/bin: %w", err)
	}
	if err := infra.WriteFiles(w); err != nil {
		return err
	}
	if err := assets.WriteTo("web-dev.mjs", filepath.Join(w.Dir(), "bin", "web-dev.mjs"), 0o644); err != nil {
		return err
	}
	for _, c := range Commands {
		if err := writeWrappers(w.Root, c); err != nil {
			return err
		}
	}
	if err := writeGitignore(w); err != nil {
		return err
	}
	removeAgentPointers(w)
	return w.Save()
}

// InstallBinary copies src to dst atomically (a running binary can be replaced on Unix; on Windows
// the old file is renamed away first because an executable in use cannot be overwritten).
func InstallBinary(src, dst string) error {
	if same(src, dst) {
		return nil
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	tmp := dst + ".new"
	out, err := os.OpenFile(tmp, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o755)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	if err := out.Close(); err != nil {
		return err
	}
	if sys.Windows {
		// A running .exe cannot be overwritten but can be renamed. Old copies are removed once no
		// process uses them any more (a ./run may still be open on one).
		olds, _ := filepath.Glob(dst + ".old*")
		for _, o := range olds {
			os.Remove(o)
		}
		if _, err := os.Stat(dst); err == nil {
			if err := os.Rename(dst, fmt.Sprintf("%s.old-%d", dst, time.Now().UnixNano())); err != nil {
				return err
			}
		}
	}
	return os.Rename(tmp, dst)
}

func same(a, b string) bool {
	sa, err1 := os.Stat(a)
	sb, err2 := os.Stat(b)
	return err1 == nil && err2 == nil && os.SameFile(sa, sb)
}

// Wrappers: `run` (sh) on macOS/Linux/WSL; `run.cmd` on Windows, where cmd and PowerShell resolve
// `.\run` to it and Git Bash runs `./run.cmd`. Only one kind exists per workspace, so `.\run` is
// never ambiguous with an extensionless file.
func writeWrappers(root, cmd string) error {
	if sys.Windows {
		os.Remove(filepath.Join(root, cmd))
		return writeCmd(root, cmd)
	}
	os.Remove(filepath.Join(root, cmd+".cmd"))
	return writeSh(root, cmd)
}

func writeSh(root, cmd string) error {
	sub := cmd
	if cmd == "ipalpha" {
		sub = "" // ./ipalpha <anything>: the full tool (config, ai, apps, update…)
	}
	sh := fmt.Sprintf(`#!/bin/sh
# Generated by IPAlpha tooling. Runs .ipalpha/bin/ipalpha %[1]s (see ./doctor if it fails).
dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
bin="$dir/.ipalpha/bin/ipalpha"
[ -x "$bin" ] || bin="$dir/.ipalpha/bin/ipalpha.exe"
if [ ! -x "$bin" ]; then
  echo "IPAlpha: $dir/.ipalpha/bin/ipalpha is missing. Re-run the setup command from the README." >&2
  exit 1
fi
exec "$bin" %[1]s "$@"
`, sub)
	if err := os.WriteFile(filepath.Join(root, cmd), []byte(sh), 0o755); err != nil {
		return err
	}
	return os.Chmod(filepath.Join(root, cmd), 0o755)
}

func writeCmd(root, cmd string) error {
	if cmd == "ipalpha" {
		cmd = ""
	}
	name := cmd
	if name == "" {
		name = "ipalpha"
	}
	bat := fmt.Sprintf("@echo off\r\nrem Generated by IPAlpha tooling. Runs .ipalpha\\bin\\ipalpha.exe %[1]s\r\n"+
		"if not exist \"%%~dp0.ipalpha\\bin\\ipalpha.exe\" (\r\n"+
		"  echo IPAlpha: %%~dp0.ipalpha\\bin\\ipalpha.exe is missing. Re-run the setup command from the README. 1>&2\r\n"+
		"  exit /b 1\r\n)\r\n"+
		"\"%%~dp0.ipalpha\\bin\\ipalpha.exe\" %[1]s %%*\r\n", cmd)
	return os.WriteFile(filepath.Join(root, name+".cmd"), []byte(bat), 0o644)
}

// The workspace root is not a repository, but people open it in editors and sometimes `git init`
// it: keep generated files out.
func writeGitignore(w *workspace.Workspace) error {
	data := "# Generated by IPAlpha tooling: local state, logs and binaries.\n*\n"
	return envfile.WriteAtomic(filepath.Join(w.Dir(), ".gitignore"), []byte(data), 0o644)
}

// removeAgentPointers deletes the CLAUDE.md / GEMINI.md / copilot-instructions.md pointers an
// earlier version of this tool generated (recognized by their marker). Agent instructions are
// personal: the tools never write or ship them; hand-written files are never touched.
func removeAgentPointers(w *workspace.Workspace) {
	const marker = "ipalpha: points to AGENTS.md"
	var dirs []string
	for _, pattern := range []string{".", "*", "*/*", "apps/*/*", "features/*", "features/*/*", "features/*/*/*", "features/*/apps/*/*"} {
		matches, _ := filepath.Glob(filepath.Join(w.Root, filepath.FromSlash(pattern)))
		dirs = append(dirs, matches...)
	}
	for _, dir := range dirs {
		if strings.Contains(filepath.ToSlash(dir), "/node_modules") {
			continue
		}
		for _, name := range []string{"CLAUDE.md", "GEMINI.md", filepath.Join(".github", "copilot-instructions.md")} {
			path := filepath.Join(dir, name)
			if data, err := os.ReadFile(path); err == nil && strings.Contains(string(data), marker) {
				os.Remove(path)
			}
		}
	}
}

// cleanLegacy removes what the bash tooling generated (it would shadow or confuse the new tools).
func cleanLegacy(w *workspace.Workspace) {
	// Only files the bash tooling generated; .ipalpha/tooling (a clone someone may have edited) and
	// anything else a developer put here stay.
	for _, name := range []string{"lib", "env-fallback", "mprocs.yaml", "projects.json", "system-clients.json"} {
		os.RemoveAll(filepath.Join(w.Dir(), name))
	}
	for _, name := range []string{"infra-up", "infra-down", "infra-logs", "install-deps", "node-dev", "web-dev", "fallback-run",
		"wait-for-http", "auth-keys-bootstrap", "browser-dev.mjs", "ipalpha-procs", "vite-dev", "build-shared-js"} {
		os.Remove(filepath.Join(w.Dir(), "bin", name))
	}
	os.RemoveAll(filepath.Join(w.Dir(), ".publish-cache"))
}
