package i18n

// messages: key → {pt-BR, en-US, es, fr, de}. Arguments use %[n]v so translations may reorder them.
var messages = map[string][5]string{}

func add(m map[string][5]string) {
	for k, v := range m {
		messages[k] = v
	}
}

func init() {
	add(map[string][5]string{
		// ── generic UI ──
		"ui_last_lines":  {"Últimas linhas:", "Last lines:", "Últimas líneas:", "Dernières lignes :", "Letzte Zeilen:"},
		"ui_how_to_fix":  {"Como resolver:", "How to fix:", "Cómo resolverlo:", "Comment corriger :", "So beheben Sie es:"},
		"ui_full_log":    {"Log completo:", "Full log:", "Log completo:", "Journal complet :", "Vollständiges Log:"},
		"ui_doctor_hint": {"Diagnóstico completo: ./doctor  ·  copie o erro com ./doctor --copy", "Full diagnosis: ./doctor  ·  copy it with ./doctor --copy", "Diagnóstico completo: ./doctor  ·  cópialo con ./doctor --copy", "Diagnostic complet : ./doctor  ·  copiez-le avec ./doctor --copy", "Vollständige Diagnose: ./doctor  ·  kopieren mit ./doctor --copy"},
		"ui_unexpected":  {"Erro inesperado", "Unexpected error", "Error inesperado", "Erreur inattendue", "Unerwarteter Fehler"},
		"ui_report_bug":  {"Isto é um bug da ferramenta. Envie o log acima para quem mantém o .github.", "This is a tool bug. Send the log above to whoever maintains .github.", "Es un error de la herramienta. Envía el log de arriba a quien mantiene .github.", "C’est un bogue de l’outil. Envoyez le journal ci-dessus à la personne qui maintient .github.", "Das ist ein Fehler im Werkzeug. Senden Sie das Log oben an die Person, die .github pflegt."},
		"ui_cancelled":   {"Cancelado.", "Cancelled.", "Cancelado.", "Annulé.", "Abgebrochen."},
		"ui_yes":         {"Sim", "Yes", "Sí", "Oui", "Ja"},
		"ui_no":          {"Não", "No", "No", "Non", "Nein"},

		// ── CLI ──
		"cli_short": {"Ferramentas de desenvolvimento do IPAlpha", "IPAlpha developer tools", "Herramientas de desarrollo de IPAlpha", "Outils de développement IPAlpha", "IPAlpha-Entwicklerwerkzeuge"},
		"cli_long": {
			"Ferramentas de desenvolvimento do IPAlpha.\n\nNo workspace use ./run, ./pull, ./publish, ./feature, ./doctor (no Windows: .\\run, .\\pull…).\nAlgo deu errado? Rode ./doctor.",
			"IPAlpha developer tools.\n\nIn the workspace use ./run, ./pull, ./publish, ./feature, ./doctor (on Windows: .\\run, .\\pull…).\nSomething went wrong? Run ./doctor.",
			"Herramientas de desarrollo de IPAlpha.\n\nEn el workspace usa ./run, ./pull, ./publish, ./feature, ./doctor (en Windows: .\\run, .\\pull…).\n¿Algo salió mal? Ejecuta ./doctor.",
			"Outils de développement IPAlpha.\n\nDans le workspace, utilisez ./run, ./pull, ./publish, ./feature, ./doctor (sous Windows : .\\run, .\\pull…).\nUn problème ? Lancez ./doctor.",
			"IPAlpha-Entwicklerwerkzeuge.\n\nIm Workspace: ./run, ./pull, ./publish, ./feature, ./doctor (unter Windows: .\\run, .\\pull…).\nEtwas ist schiefgelaufen? Führen Sie ./doctor aus."},
		"cli_no_workspace_step": {"Encontrar o workspace", "Find the workspace", "Encontrar el workspace", "Trouver le workspace", "Workspace finden"},
		"cli_no_workspace":      {"Esta pasta não está dentro de um workspace do IPAlpha (falta .ipalpha/settings).", "This folder is not inside an IPAlpha workspace (.ipalpha/settings is missing).", "Esta carpeta no está dentro de un workspace de IPAlpha (falta .ipalpha/settings).", "Ce dossier n’est pas dans un workspace IPAlpha (.ipalpha/settings manquant).", "Dieser Ordner liegt nicht in einem IPAlpha-Workspace (.ipalpha/settings fehlt)."},
		"cli_fix_cd":            {"Entre na pasta do workspace (ex.: cd IpAlpha) e rode de novo.", "Go into the workspace folder (e.g. cd IpAlpha) and run it again.", "Entra en la carpeta del workspace (p. ej. cd IpAlpha) y vuelve a ejecutarlo.", "Placez-vous dans le dossier du workspace (ex. : cd IpAlpha) et relancez.", "Wechseln Sie in den Workspace-Ordner (z. B. cd IpAlpha) und starten Sie erneut."},
		"cli_fix_setup":         {"Ainda não tem workspace? Rode o comando de setup do README.", "No workspace yet? Run the setup command from the README.", "¿Aún no tienes workspace? Ejecuta el comando de setup del README.", "Pas encore de workspace ? Lancez la commande de setup du README.", "Noch kein Workspace? Führen Sie den Setup-Befehl aus der README aus."},

		// ── command descriptions ──
		"cmd_setup":      {"Prepara um workspace novo (ou repara um existente)", "Prepare a new workspace (or repair an existing one)", "Prepara un workspace nuevo (o repara uno existente)", "Prépare un nouveau workspace (ou répare un existant)", "Neuen Workspace einrichten (oder bestehenden reparieren)"},
		"cmd_setup_long": {"Verifica e instala ferramentas, clona os repositórios, cria os .env, pergunta o primeiro acesso e a IA, e gera ./run ./pull ./publish ./feature. Pode rodar de novo a qualquer momento: nada que você configurou é sobrescrito.", "Checks and installs tools, clones the repositories, creates the .env files, asks for the first sign-in and the AI, and writes ./run ./pull ./publish ./feature. Safe to run again at any time: nothing you configured is overwritten.", "Verifica e instala herramientas, clona los repositorios, crea los .env, pregunta el primer acceso y la IA, y genera ./run ./pull ./publish ./feature. Puedes volver a ejecutarlo: nada de lo que configuraste se sobrescribe.", "Vérifie et installe les outils, clone les dépôts, crée les .env, demande le premier accès et l’IA, puis génère ./run ./pull ./publish ./feature. Relançable à tout moment : rien de ce que vous avez configuré n’est écrasé.", "Prüft und installiert Werkzeuge, klont die Repositories, legt die .env-Dateien an, fragt nach der ersten Anmeldung und der KI und erzeugt ./run ./pull ./publish ./feature. Jederzeit erneut ausführbar: Ihre Einstellungen bleiben erhalten."},
		"cmd_run":        {"Sobe a infra, as APIs e os web apps no painel", "Start the infra, APIs and web apps in the panel", "Levanta la infra, las APIs y las web apps en el panel", "Démarre l’infra, les API et les applications web dans le panneau", "Startet Infrastruktur, APIs und Web-Apps im Panel"},
		"cmd_run_long": {
			"Sobe MongoDB, Redis, RabbitMQ e Mailpit; instala dependências; inicia cada API e os web apps lembrados. Porta ocupada? O serviço muda para uma livre só nesta execução e tudo continua funcionando. Pressione ? no painel para ver as teclas.",
			"Starts MongoDB, Redis, RabbitMQ and Mailpit; installs dependencies; starts every API and the remembered web apps. Busy port? The service moves to a free one for this run and everything keeps working. Press ? in the panel for the keys.",
			"Levanta MongoDB, Redis, RabbitMQ y Mailpit; instala dependencias; inicia cada API y las web apps recordadas. ¿Puerto ocupado? El servicio pasa a uno libre solo en esta ejecución y todo sigue funcionando. Pulsa ? en el panel para ver las teclas.",
			"Démarre MongoDB, Redis, RabbitMQ et Mailpit ; installe les dépendances ; lance chaque API et les applications web mémorisées. Port occupé ? Le service passe sur un port libre pour cette exécution et tout continue de fonctionner. Appuyez sur ? dans le panneau pour voir les touches.",
			"Startet MongoDB, Redis, RabbitMQ und Mailpit, installiert Abhängigkeiten und startet jede API und die gemerkten Web-Apps. Port belegt? Der Dienst weicht für diesen Lauf auf einen freien Port aus, alles funktioniert weiter. Drücken Sie ? im Panel für die Tasten."},
		"cmd_stop":      {"Para a infra (contêineres ficam para subir rápido)", "Stop the infra (containers are kept for a fast start)", "Detiene la infra (los contenedores se conservan)", "Arrête l’infra (les conteneurs sont conservés)", "Stoppt die Infrastruktur (Container bleiben erhalten)"},
		"cmd_stop_long": {"--purge remove os contêineres (dados ficam). --volumes também apaga os dados locais.", "--purge removes the containers (data is kept). --volumes also deletes local data.", "--purge elimina los contenedores (los datos se conservan). --volumes también borra los datos locales.", "--purge supprime les conteneurs (les données restent). --volumes efface aussi les données locales.", "--purge entfernt die Container (Daten bleiben). --volumes löscht auch die lokalen Daten."},
		"cmd_status":    {"Mostra o que está rodando e em quais portas", "Show what is running and on which ports", "Muestra qué está corriendo y en qué puertos", "Affiche ce qui tourne et sur quels ports", "Zeigt, was läuft und auf welchen Ports"},
		"cmd_logs":      {"Mostra os logs de um serviço (./logs auth-api -f)", "Show a service's logs (./logs auth-api -f)", "Muestra los logs de un servicio (./logs auth-api -f)", "Affiche les journaux d’un service (./logs auth-api -f)", "Zeigt die Logs eines Dienstes (./logs auth-api -f)"},
		"cmd_pull":      {"Atualiza repositórios, .env e as ferramentas", "Update repositories, .env files and the tools", "Actualiza repositorios, .env y las herramientas", "Met à jour les dépôts, les .env et les outils", "Aktualisiert Repositories, .env-Dateien und Werkzeuge"},
		"cmd_pull_long": {"Baixa a versão nova da ferramenta, faz pull fast-forward de cada repositório (conflito deixa a pasta como está), clona os que faltam e adiciona chaves novas aos .env sem mudar seus valores.", "Downloads the new tool version, fast-forwards every repository (a conflict leaves that folder untouched), clones missing ones and adds new keys to the .env files without changing your values.", "Descarga la nueva versión de la herramienta, hace pull fast-forward de cada repositorio (un conflicto deja la carpeta igual), clona los que faltan y añade claves nuevas a los .env sin cambiar tus valores.", "Télécharge la nouvelle version de l’outil, avance chaque dépôt en fast-forward (un conflit laisse le dossier intact), clone ceux qui manquent et ajoute les nouvelles clés aux .env sans changer vos valeurs.", "Lädt die neue Werkzeugversion, aktualisiert jedes Repository per Fast-Forward (bei Konflikt bleibt der Ordner unverändert), klont fehlende und ergänzt neue Schlüssel in den .env-Dateien, ohne Ihre Werte zu ändern."},
		"cmd_publish":   {"Publica os repositórios alterados (versão + commit pela IA)", "Publish changed repositories (AI picks version + commit)", "Publica los repositorios modificados (la IA elige versión y commit)", "Publie les dépôts modifiés (l’IA choisit version et commit)", "Veröffentlicht geänderte Repositories (KI wählt Version und Commit)"},
		"cmd_publish_long": {
			"Detecta repositórios alterados, a IA escolhida propõe o bump semver e a mensagem (ou você digita se ela falhar), faz commit/push, publica o shared-js no npm, gera imagens e atualiza deployment.\nDentro de features/<slug>, publica o preview da feature.\n\n./publish -d mostra o plano sem mudar nada · ./publish clean limpa o cache de decisões.",
			"Detects changed repositories, the chosen AI proposes the semver bump and message (or you type them when it fails), commits/pushes, publishes shared-js to npm, builds images and updates deployment.\nInside features/<slug>, publishes that feature's preview.\n\n./publish -d shows the plan without changing anything · ./publish clean wipes the decision cache.",
			"Detecta repositorios modificados, la IA elegida propone el bump semver y el mensaje (o los escribes si falla), hace commit/push, publica shared-js en npm, genera imágenes y actualiza deployment.\nDentro de features/<slug>, publica el preview de la feature.\n\n./publish -d muestra el plan sin cambiar nada · ./publish clean limpia la caché de decisiones.",
			"Détecte les dépôts modifiés ; l’IA choisie propose le bump semver et le message (ou vous les saisissez si elle échoue) ; commit/push, publie shared-js sur npm, construit les images et met à jour deployment.\nDans features/<slug>, publie la préversion de la feature.\n\n./publish -d montre le plan sans rien changer · ./publish clean vide le cache des décisions.",
			"Erkennt geänderte Repositories; die gewählte KI schlägt Semver-Bump und Nachricht vor (oder Sie tippen sie bei einem Fehler selbst ein); Commit/Push, shared-js auf npm, Images bauen, deployment aktualisieren.\nIn features/<slug> wird die Vorschau der Feature veröffentlicht.\n\n./publish -d zeigt den Plan ohne Änderungen · ./publish clean leert den Entscheidungs-Cache."},
		"cmd_feature":         {"Ambientes de feature e previews", "Feature environments and previews", "Entornos de feature y previews", "Environnements de feature et préversions", "Feature-Umgebungen und Vorschauen"},
		"cmd_feature_long":    {"Um workspace isolado por feature (worktrees em feat/<slug>) com seu preview público. Guia: docs/local-development.md.", "One isolated workspace per feature (worktrees on feat/<slug>) with its public preview. Guide: docs/local-development.md.", "Un workspace aislado por feature (worktrees en feat/<slug>) con su preview público. Guía: docs/local-development.md.", "Un workspace isolé par feature (worktrees sur feat/<slug>) avec sa préversion publique. Guide : docs/local-development.md.", "Ein isolierter Workspace pro Feature (Worktrees auf feat/<slug>) mit öffentlicher Vorschau. Anleitung: docs/local-development.md."},
		"cmd_feature_new":     {"Cria features/<slug> a partir do último Core Deploy verde", "Create features/<slug> from the last green Core Deploy", "Crea features/<slug> desde el último Core Deploy verde", "Crée features/<slug> depuis le dernier Core Deploy vert", "Erstellt features/<slug> aus dem letzten grünen Core Deploy"},
		"cmd_feature_list":    {"Lista previews publicados e features locais", "List published previews and local features", "Lista previews publicados y features locales", "Liste les préversions publiées et les features locales", "Listet veröffentlichte Vorschauen und lokale Features"},
		"cmd_feature_rebase":  {"Move a base para o último Core Deploy verde", "Move the baseline to the last green Core Deploy", "Mueve la base al último Core Deploy verde", "Déplace la base vers le dernier Core Deploy vert", "Verschiebt die Basis auf den letzten grünen Core Deploy"},
		"cmd_feature_extend":  {"Mantém o preview por mais 72 h", "Keep the preview 72 more hours", "Mantiene el preview 72 h más", "Prolonge la préversion de 72 h", "Hält die Vorschau 72 h länger"},
		"cmd_feature_reset":   {"Volta o preview aos dados sintéticos", "Reset the preview to the synthetic data", "Restablece el preview a los datos sintéticos", "Réinitialise la préversion aux données synthétiques", "Setzt die Vorschau auf die synthetischen Daten zurück"},
		"cmd_feature_destroy": {"Apaga o preview e os worktrees (branches ficam)", "Delete the preview and the worktrees (branches are kept)", "Borra el preview y los worktrees (las ramas se conservan)", "Supprime la préversion et les worktrees (les branches restent)", "Löscht Vorschau und Worktrees (Branches bleiben)"},
		"cmd_ai":              {"Escolhe a IA e o modelo usados pelo ./publish", "Choose the AI and model ./publish uses", "Elige la IA y el modelo que usa ./publish", "Choisit l’IA et le modèle utilisés par ./publish", "Wählt KI und Modell für ./publish"},
		"cmd_ai_long":         {"Qualquer CLI de IA (pi, claude, codex, gemini, opencode, copilot, grok, ollama) ou um comando seu, com qualquer modelo. Fica em .ipalpha/settings deste workspace.", "Any AI CLI (pi, claude, codex, gemini, opencode, copilot, grok, ollama) or your own command, with any model. Stored in this workspace's .ipalpha/settings.", "Cualquier CLI de IA (pi, claude, codex, gemini, opencode, copilot, grok, ollama) o tu propio comando, con cualquier modelo. Se guarda en .ipalpha/settings de este workspace.", "N’importe quel CLI d’IA (pi, claude, codex, gemini, opencode, copilot, grok, ollama) ou votre propre commande, avec n’importe quel modèle. Enregistré dans .ipalpha/settings de ce workspace.", "Jede KI-CLI (pi, claude, codex, gemini, opencode, copilot, grok, ollama) oder ein eigener Befehl, mit jedem Modell. Gespeichert in .ipalpha/settings dieses Workspaces."},
		"cmd_ai_test":         {"Testa a IA configurada", "Test the configured AI", "Prueba la IA configurada", "Teste l’IA configurée", "Testet die konfigurierte KI"},
		"cmd_ai_set":          {"Define a IA sem perguntas (ipalpha ai set claude sonnet)", "Set the AI without questions (ipalpha ai set claude sonnet)", "Define la IA sin preguntas (ipalpha ai set claude sonnet)", "Définit l’IA sans questions (ipalpha ai set claude sonnet)", "Setzt die KI ohne Rückfragen (ipalpha ai set claude sonnet)"},
		"cmd_config":          {"Muda idioma, IA, apps, portas e runtime", "Change language, AI, apps, ports and runtime", "Cambia idioma, IA, apps, puertos y runtime", "Modifie langue, IA, apps, ports et runtime", "Ändert Sprache, KI, Apps, Ports und Runtime"},
		"cmd_config_long":     {"Menu interativo. Também: ipalpha config get [chave] · ipalpha config set <chave> <valor>.", "Interactive menu. Also: ipalpha config get [key] · ipalpha config set <key> <value>.", "Menú interactivo. También: ipalpha config get [clave] · ipalpha config set <clave> <valor>.", "Menu interactif. Aussi : ipalpha config get [clé] · ipalpha config set <clé> <valeur>.", "Interaktives Menü. Außerdem: ipalpha config get [Schlüssel] · ipalpha config set <Schlüssel> <Wert>."},
		"cmd_config_get":      {"Mostra as configurações", "Show the settings", "Muestra la configuración", "Affiche les réglages", "Zeigt die Einstellungen"},
		"cmd_config_set":      {"Muda uma configuração", "Change one setting", "Cambia un ajuste", "Modifie un réglage", "Ändert eine Einstellung"},
		"cmd_doctor":          {"Diagnostica ferramentas, workspace, portas e IA", "Diagnose tools, workspace, ports and AI", "Diagnostica herramientas, workspace, puertos e IA", "Diagnostique outils, workspace, ports et IA", "Prüft Werkzeuge, Workspace, Ports und KI"},
		"cmd_doctor_long":     {"Lista o que está faltando ou quebrado com a correção de cada item. --ai também testa a IA; --copy copia o relatório para enviar a alguém.", "Lists what is missing or broken with the fix for each item. --ai also tests the AI; --copy copies the report to send to someone.", "Lista lo que falta o está roto con la corrección de cada ítem. --ai también prueba la IA; --copy copia el informe para enviarlo.", "Liste ce qui manque ou est cassé avec la correction de chaque élément. --ai teste aussi l’IA ; --copy copie le rapport pour l’envoyer.", "Listet Fehlendes oder Defektes samt Lösung. --ai testet auch die KI; --copy kopiert den Bericht zum Weitergeben."},
		"cmd_set_keys":        {"Configura primeiro acesso e chaves locais", "Configure the first sign-in and local keys", "Configura el primer acceso y las claves locales", "Configure le premier accès et les clés locales", "Erste Anmeldung und lokale Schlüssel einrichten"},
		"cmd_set_keys_long":   {"Pergunta o nome e o celular do primeiro acesso e, opcionalmente, chaves de SMS (só usadas fora do ambiente local).", "Asks for the first sign-in's name and mobile number and, optionally, SMS keys (only used outside the local environment).", "Pregunta el nombre y el móvil del primer acceso y, opcionalmente, claves de SMS (solo se usan fuera del entorno local).", "Demande le nom et le portable du premier accès et, en option, des clés SMS (utilisées uniquement hors environnement local).", "Fragt Name und Mobilnummer der ersten Anmeldung und optional SMS-Schlüssel ab (nur außerhalb der lokalen Umgebung genutzt)."},
		"cmd_apps":            {"Escolhe quais web apps sobem e quais páginas abrem", "Choose which web apps start and which pages open", "Elige qué web apps se inician y qué páginas se abren", "Choisit quelles applications web démarrent et quelles pages s’ouvrent", "Wählt, welche Web-Apps starten und welche Seiten sich öffnen"},
		"cmd_apps_long":       {"A escolha fica salva; o ./run seguinte respeita. Também: ./run apps set <app…> · ./run apps defaults.", "The choice is saved; the next ./run follows it. Also: ./run apps set <app…> · ./run apps defaults.", "La elección se guarda; el siguiente ./run la respeta. También: ./run apps set <app…> · ./run apps defaults.", "Le choix est enregistré ; le prochain ./run le suit. Aussi : ./run apps set <app…> · ./run apps defaults.", "Die Auswahl wird gespeichert; der nächste ./run folgt ihr. Außerdem: ./run apps set <App…> · ./run apps defaults."},
		"cmd_apps_set":        {"Define a lista (vazia = nenhum)", "Set the list (empty = none)", "Define la lista (vacía = ninguna)", "Définit la liste (vide = aucune)", "Setzt die Liste (leer = keine)"},
		"cmd_apps_defaults":   {"Volta ao padrão (Auth, Oikos, Mailpit)", "Back to defaults (Auth, Oikos, Mailpit)", "Vuelve al estándar (Auth, Oikos, Mailpit)", "Revient aux valeurs par défaut (Auth, Oikos, Mailpit)", "Zurück zum Standard (Auth, Oikos, Mailpit)"},
		"cmd_apps_list":       {"Mostra a lista atual", "Show the current list", "Muestra la lista actual", "Affiche la liste actuelle", "Zeigt die aktuelle Liste"},
		"cmd_update":          {"Baixa a versão mais nova da ferramenta", "Download the newest tool version", "Descarga la versión más nueva de la herramienta", "Télécharge la dernière version de l’outil", "Lädt die neueste Werkzeugversion"},

		// ── flags ──
		"flag_skip_tools":      {"não verificar/instalar ferramentas", "do not check/install tools", "no verificar/instalar herramientas", "ne pas vérifier/installer les outils", "Werkzeuge nicht prüfen/installieren"},
		"flag_skip_install":    {"não instalar dependências npm", "do not install npm dependencies", "no instalar dependencias npm", "ne pas installer les dépendances npm", "keine npm-Abhängigkeiten installieren"},
		"flag_yes":             {"aceitar os padrões sem perguntar", "accept defaults without asking", "aceptar los valores por defecto sin preguntar", "accepter les valeurs par défaut sans demander", "Standardwerte ohne Rückfrage übernehmen"},
		"flag_plain":           {"sem painel: logs com prefixo (CI, terminais simples)", "no panel: prefixed logs (CI, simple terminals)", "sin panel: logs con prefijo (CI, terminales simples)", "sans panneau : journaux préfixés (CI, terminaux simples)", "ohne Panel: Logs mit Präfix (CI, einfache Terminals)"},
		"flag_skip_deps":       {"não verificar dependências npm", "do not check npm dependencies", "no verificar dependencias npm", "ne pas vérifier les dépendances npm", "npm-Abhängigkeiten nicht prüfen"},
		"flag_no_browser":      {"não abrir páginas no navegador desta vez", "do not open browser pages this time", "no abrir páginas en el navegador esta vez", "ne pas ouvrir de pages cette fois", "diesmal keine Browserseiten öffnen"},
		"flag_only":            {"iniciar só estes serviços (ex.: --only auth-api,persons-api)", "start only these services (e.g. --only auth-api,persons-api)", "iniciar solo estos servicios (p. ej. --only auth-api,persons-api)", "ne démarrer que ces services (ex. : --only auth-api,persons-api)", "nur diese Dienste starten (z. B. --only auth-api,persons-api)"},
		"flag_until_ready":     {"sai com sucesso quando tudo estiver pronto (ex.: --until-ready 5m)", "exit successfully once everything is ready (e.g. --until-ready 5m)", "sale con éxito cuando todo esté listo (p. ej. --until-ready 5m)", "quitte avec succès quand tout est prêt (ex. : --until-ready 5m)", "erfolgreich beenden, sobald alles bereit ist (z. B. --until-ready 5m)"},
		"flag_purge":           {"remover os contêineres (dados ficam)", "remove the containers (data is kept)", "eliminar los contenedores (los datos se conservan)", "supprimer les conteneurs (les données restent)", "Container entfernen (Daten bleiben)"},
		"flag_volumes":         {"também apagar os dados locais (pede confirmação)", "also delete local data (asks for confirmation)", "también borrar los datos locales (pide confirmación)", "effacer aussi les données locales (demande confirmation)", "auch lokale Daten löschen (mit Bestätigung)"},
		"flag_follow":          {"continuar mostrando o que chega", "keep showing new output", "seguir mostrando lo nuevo", "continuer d’afficher la suite", "neue Ausgaben weiter anzeigen"},
		"flag_no_update":       {"não baixar versão nova da ferramenta", "do not download a new tool version", "no descargar versión nueva de la herramienta", "ne pas télécharger de nouvelle version", "keine neue Werkzeugversion laden"},
		"flag_dry_run":         {"mostrar o plano sem mudar nada", "show the plan without changing anything", "mostrar el plan sin cambiar nada", "montrer le plan sans rien changer", "Plan zeigen, ohne etwas zu ändern"},
		"flag_folder":          {"só este repositório", "only this repository", "solo este repositorio", "uniquement ce dépôt", "nur dieses Repository"},
		"flag_engine":          {"CLI de IA só nesta execução", "AI CLI for this run only", "CLI de IA solo en esta ejecución", "CLI d’IA pour cette exécution seulement", "KI-CLI nur für diesen Lauf"},
		"flag_model":           {"modelo de IA só nesta execução", "AI model for this run only", "modelo de IA solo en esta ejecución", "modèle d’IA pour cette exécution seulement", "KI-Modell nur für diesen Lauf"},
		"flag_ci":              {"o TeamCity gera as imagens (sem docker build local)", "TeamCity builds the images (no local docker build)", "TeamCity genera las imágenes (sin docker build local)", "TeamCity construit les images (pas de docker build local)", "TeamCity baut die Images (kein lokales docker build)"},
		"flag_initialize":      {"inicializa um repositório privado novo", "initialize a new private repository", "inicializa un repositorio privado nuevo", "initialise un nouveau dépôt privé", "neues privates Repository anlegen"},
		"flag_npm_only":        {"publica no npm o shared-js já marcado", "publish the already tagged shared-js to npm", "publica en npm el shared-js ya etiquetado", "publie sur npm le shared-js déjà étiqueté", "bereits getaggtes shared-js auf npm veröffentlichen"},
		"flag_resume":          {"retoma uma imagem já versionada (sem novo bump)", "resume an already versioned image (no new bump)", "retoma una imagen ya versionada (sin nuevo bump)", "reprend une image déjà versionnée (sans nouveau bump)", "bereits versioniertes Image fortsetzen (kein neuer Bump)"},
		"flag_deployment_path": {"publica um arquivo não secreto de deployment", "publish a non-secret deployment file", "publica un archivo no secreto de deployment", "publie un fichier deployment non secret", "nicht geheime deployment-Datei veröffentlichen"},
		"flag_message":         {"mensagem do commit de deployment", "deployment commit message", "mensaje del commit de deployment", "message du commit deployment", "Commit-Nachricht für deployment"},
		"flag_feature":         {"publica o preview desta feature", "publish this feature's preview", "publica el preview de esta feature", "publie la préversion de cette feature", "Vorschau dieser Feature veröffentlichen"},
		"flag_no_wait":         {"não esperar o pipeline Preview", "do not wait for the Preview pipeline", "no esperar el pipeline Preview", "ne pas attendre le pipeline Preview", "nicht auf die Preview-Pipeline warten"},
		"flag_baseline":        {"base registrada antes (commit do deployment master)", "an earlier recorded baseline (deployment master commit)", "base registrada antes (commit de deployment master)", "base enregistrée plus tôt (commit de deployment master)", "früher erfasste Basis (Commit auf deployment master)"},
		"flag_force":           {"apagar mesmo com mudanças locais", "delete even with local changes", "borrar aun con cambios locales", "supprimer même avec des modifications locales", "auch mit lokalen Änderungen löschen"},
		"flag_doctor_ai":       {"também testa a IA (pode levar 1 min)", "also test the AI (may take 1 min)", "también prueba la IA (puede tardar 1 min)", "teste aussi l’IA (peut prendre 1 min)", "testet auch die KI (kann 1 Min. dauern)"},
		"flag_doctor_copy":     {"copia o relatório para a área de transferência", "copy the report to the clipboard", "copia el informe al portapapeles", "copie le rapport dans le presse-papiers", "kopiert den Bericht in die Zwischenablage"},
	})
}
