#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
const valueOf = (flag) => {
  const i = args.indexOf(flag);
  return i >= 0 ? args[i + 1] : undefined;
};
const scriptRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const policyDir = path.resolve(valueOf('--policy') || path.join(scriptRoot, 'policy'));
const workspace = valueOf('--workspace') ? path.resolve(valueOf('--workspace')) : null;
const requireProfiles = args.includes('--require-profiles');
const failures = [];
const fail = (message) => failures.push(message);

const required = [
  'README.md', 'SECURITY_BASELINE.md', 'DATA_CLASSIFICATION.md',
  'IDENTITY_AND_AUTHORIZATION.md', 'APP_TRUST_AND_APPROVAL.md',
  'AI_AND_EXTERNAL_PROCESSORS.md', 'SECRETS_AND_CONFIGURATION.md',
  'LOGGING_AND_AUDIT.md', 'FRONTEND_MOBILE_AND_OFFLINE.md',
  'API_AND_INTEGRATION_SECURITY.md', 'DATA_LIFECYCLE.md',
  'DEVELOPMENT_ENVIRONMENTS.md', 'SECURE_DELIVERY.md',
  'INCIDENT_RESPONSE.md', 'SECURITY_EXCEPTIONS.md', 'policy.yaml',
  'templates/repository-AGENTS.md', 'templates/security-profile.md',
  'templates/ai-integration-review.md', 'templates/security-exception.md',
  'templates/change-security-checklist.md',
];

for (const relative of required) {
  const file = path.join(policyDir, relative);
  if (!fs.existsSync(file)) fail(`missing policy file: ${relative}`);
  else if (!fs.statSync(file).size) fail(`empty policy file: ${relative}`);
}

const yaml = fs.existsSync(path.join(policyDir, 'policy.yaml'))
  ? fs.readFileSync(path.join(policyDir, 'policy.yaml'), 'utf8') : '';
for (const key of ['version:', 'classes:', 'invariants:', 'requiredDocuments:', 'minimumGates:', 'stopConditions:']) {
  if (!yaml.includes(`\n${key}`) && !yaml.startsWith(key)) fail(`policy.yaml missing top-level key: ${key.slice(0, -1)}`);
}
for (const name of required.filter((x) => x.endsWith('.md') && !x.startsWith('templates/'))) {
  if (yaml && !yaml.includes(`- ${name}`)) fail(`policy.yaml requiredDocuments missing: ${name}`);
}

const markdownFiles = required.filter((x) => x.endsWith('.md')).map((x) => path.join(policyDir, x));
for (const file of markdownFiles.filter(fs.existsSync)) {
  const text = fs.readFileSync(file, 'utf8');
  if (/^(<{7}|={7}|>{7})/m.test(text)) fail(`merge conflict marker: ${path.relative(policyDir, file)}`);
  const links = [...text.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)].map((m) => m[1]);
  for (const target of links) {
    if (/^(https?:|mailto:|#)/.test(target)) continue;
    const clean = target.split('#')[0];
    if (clean && !fs.existsSync(path.resolve(path.dirname(file), clean))) {
      fail(`broken local link in ${path.relative(policyDir, file)}: ${target}`);
    }
  }
}

function gitRepos(root) {
  if (!root || !fs.existsSync(root)) return [];
  const out = [];
  const visit = (dir, depth) => {
    if (depth > 4) return;
    if (fs.existsSync(path.join(dir, '.git'))) { out.push(dir); return; }
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory() || ['node_modules', '.ipalpha', 'features'].includes(entry.name)) continue;
      visit(path.join(dir, entry.name), depth + 1);
    }
  };
  visit(root, 0);
  return out;
}

if (workspace) {
  const agents = path.join(workspace, 'AGENTS.md');
  if (!fs.existsSync(agents)) fail('workspace AGENTS.md is missing');
  else if (!fs.readFileSync(agents, 'utf8').startsWith('<!-- Generated by ipalpha-dev/.github.')) {
    fail('workspace AGENTS.md is not the managed IPAlpha entry point');
  }
  const localYaml = path.join(workspace, '.ipalpha/policy/policy.yaml');
  if (!fs.existsSync(localYaml)) fail('workspace policy copy is missing');
  else {
    const version = (yaml.match(/^version:\s*(.+)$/m) || [])[1];
    const localVersion = (fs.readFileSync(localYaml, 'utf8').match(/^version:\s*(.+)$/m) || [])[1];
    if (version !== localVersion) fail(`workspace policy version drift: canonical=${version} local=${localVersion}`);
  }

  for (const repo of gitRepos(workspace)) {
    let tracked = [];
    try {
      tracked = execFileSync('git', ['-C', repo, 'ls-files'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).split(/\r?\n/).filter(Boolean);
    } catch { continue; }
    for (const file of tracked) {
      const normalized = file.replaceAll('\\', '/');
      const base = path.posix.basename(normalized).toLowerCase();
      if ((base === '.env' || base.startsWith('.env.')) && base !== '.env.example') fail(`${path.basename(repo)} tracks forbidden environment file: ${file}`);
      if (/\.(pem|p12|pfx|jks|keystore)$/i.test(base)) fail(`${path.basename(repo)} tracks forbidden key container: ${file}`);
    }
    if (requireProfiles) {
      if (!tracked.includes('AGENTS.md')) fail(`${path.basename(repo)} has no AGENTS.md`);
      if (!tracked.includes('docs/security-profile.md')) fail(`${path.basename(repo)} has no docs/security-profile.md`);
    }
  }
}

if (failures.length) {
  console.error('IPAlpha policy check failed:');
  for (const message of failures) console.error(`  - ${message}`);
  process.exit(1);
}
console.log(`IPAlpha policy check passed (policy ${((yaml.match(/^version:\s*(.+)$/m) || [])[1] || 'unknown')}).`);
